/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author miwoj2051
 */
public class FamilybudgetProgram extends javax.swing.JFrame {
double life, transportation, savings, housing, monthlyIncome; 
double lifeP, transportationP, savingsP, housingP;
String savingsB;
    /**
     * Creates new form FamilybudgetProgram
     */
    public FamilybudgetProgram() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        familyBudget = new javax.swing.JPanel();
        heading = new javax.swing.JLabel();
        prompt = new javax.swing.JLabel();
        housingPrompt = new javax.swing.JLabel();
        transportationPrompt = new javax.swing.JLabel();
        lifePrompt = new javax.swing.JLabel();
        savingsPrompt = new javax.swing.JLabel();
        housingInput = new javax.swing.JTextField();
        transportationInput = new javax.swing.JTextField();
        lifeInput = new javax.swing.JTextField();
        savingsInput = new javax.swing.JTextField();
        monthlyIncomePrompt = new javax.swing.JLabel();
        monthlyIncomeInput = new javax.swing.JTextField();
        Enter = new javax.swing.JButton();
        monthlySpending = new javax.swing.JPanel();
        heading2 = new javax.swing.JLabel();
        housingT = new javax.swing.JLabel();
        trasnportationT = new javax.swing.JLabel();
        lifeT = new javax.swing.JLabel();
        savingsT = new javax.swing.JLabel();
        housingBar = new javax.swing.JLabel();
        transportationBar = new javax.swing.JLabel();
        lifeBar = new javax.swing.JLabel();
        savingsBar = new javax.swing.JLabel();
        budgetResults = new javax.swing.JPanel();
        housingRules = new javax.swing.JLabel();
        transportationRules = new javax.swing.JLabel();
        lifeRules = new javax.swing.JLabel();
        savingsRules = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        familyBudget.setBackground(new java.awt.Color(255, 153, 255));

        heading.setText("Family Budget");

        prompt.setText("Enter the amount you spend in each category per month:");

        housingPrompt.setText("Housing:");

        transportationPrompt.setText("Transportation:");

        lifePrompt.setText("Life:");

        savingsPrompt.setText("Savings:");

        housingInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                housingInputActionPerformed(evt);
            }
        });

        monthlyIncomePrompt.setText("Enter your net monthly income:");

        monthlyIncomeInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthlyIncomeInputActionPerformed(evt);
            }
        });

        Enter.setText("Enter");
        Enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout familyBudgetLayout = new javax.swing.GroupLayout(familyBudget);
        familyBudget.setLayout(familyBudgetLayout);
        familyBudgetLayout.setHorizontalGroup(
            familyBudgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, familyBudgetLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(heading, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133))
            .addGroup(familyBudgetLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(familyBudgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prompt, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(familyBudgetLayout.createSequentialGroup()
                        .addGroup(familyBudgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, familyBudgetLayout.createSequentialGroup()
                                .addComponent(housingPrompt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(housingInput, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, familyBudgetLayout.createSequentialGroup()
                                .addComponent(transportationPrompt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(transportationInput, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(familyBudgetLayout.createSequentialGroup()
                                .addGroup(familyBudgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lifePrompt)
                                    .addComponent(savingsPrompt))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(familyBudgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(savingsInput, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lifeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(familyBudgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(familyBudgetLayout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(familyBudgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(monthlyIncomePrompt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(monthlyIncomeInput)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, familyBudgetLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Enter)
                                .addGap(52, 52, 52)))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        familyBudgetLayout.setVerticalGroup(
            familyBudgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(familyBudgetLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(heading, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prompt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(familyBudgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(housingPrompt)
                    .addComponent(housingInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monthlyIncomePrompt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(familyBudgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transportationPrompt)
                    .addComponent(transportationInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monthlyIncomeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(familyBudgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lifePrompt)
                    .addComponent(lifeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Enter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(familyBudgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savingsPrompt)
                    .addComponent(savingsInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        monthlySpending.setBackground(new java.awt.Color(102, 255, 102));

        heading2.setText("Monthly Spending");

        housingT.setText("Housing:");

        trasnportationT.setText("Transportation:");

        lifeT.setText("Life:");

        savingsT.setText("Savings:");

        javax.swing.GroupLayout monthlySpendingLayout = new javax.swing.GroupLayout(monthlySpending);
        monthlySpending.setLayout(monthlySpendingLayout);
        monthlySpendingLayout.setHorizontalGroup(
            monthlySpendingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(monthlySpendingLayout.createSequentialGroup()
                .addGroup(monthlySpendingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(monthlySpendingLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(heading2))
                    .addGroup(monthlySpendingLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(housingT)
                        .addGap(18, 18, 18)
                        .addComponent(housingBar, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(monthlySpendingLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(savingsT)
                        .addGap(40, 40, 40)
                        .addComponent(savingsBar, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(monthlySpendingLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(monthlySpendingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(trasnportationT)
                            .addComponent(lifeT))
                        .addGap(18, 18, 18)
                        .addGroup(monthlySpendingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(transportationBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(monthlySpendingLayout.createSequentialGroup()
                                .addComponent(lifeBar, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        monthlySpendingLayout.setVerticalGroup(
            monthlySpendingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(monthlySpendingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(heading2)
                .addGap(18, 18, 18)
                .addGroup(monthlySpendingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(monthlySpendingLayout.createSequentialGroup()
                        .addComponent(housingBar, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addGroup(monthlySpendingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(trasnportationT)
                            .addComponent(transportationBar, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(monthlySpendingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lifeT)
                            .addComponent(lifeBar, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(monthlySpendingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(savingsT)
                            .addComponent(savingsBar, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(housingT))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        budgetResults.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout budgetResultsLayout = new javax.swing.GroupLayout(budgetResults);
        budgetResults.setLayout(budgetResultsLayout);
        budgetResultsLayout.setHorizontalGroup(
            budgetResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(budgetResultsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(budgetResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(savingsRules, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, budgetResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(housingRules, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(transportationRules, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lifeRules, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        budgetResultsLayout.setVerticalGroup(
            budgetResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(budgetResultsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(housingRules, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(transportationRules, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lifeRules, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(savingsRules, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(familyBudget, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(monthlySpending, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(budgetResults, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(familyBudget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(monthlySpending, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(budgetResults, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void housingInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_housingInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_housingInputActionPerformed

    private void monthlyIncomeInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthlyIncomeInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthlyIncomeInputActionPerformed

    private void EnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterActionPerformed
        savings = Double.parseDouble(savingsInput.getText());
        transportation = Double.parseDouble(transportationInput.getText());
        housing = Double.parseDouble(housingInput.getText());
        life = Double.parseDouble(lifeInput.getText());
        monthlyIncome = Double.parseDouble(monthlyIncomeInput.getText());
        
        savingsP = savings*100/monthlyIncome;
        lifeP = life*100/monthlyIncome;
        housingP = housing*100/monthlyIncome;
        transportationP = transportation*100/monthlyIncome;
        
        for (int i = 0; i<savingsP; i++){
        savingsB += " "; 
        savingsBar.setText(savingsB);
        }
        
        if(housingP>35){
            housingRules.setText("You are spending too much on housing");
        } else {
             housingRules.setText("Housing is fine");
                }
        if(transportationP>15){
            transportationRules.setText("You are spending too much on transportation");
        }else{
            transportationRules.setText("Transportation is fine");
        }
        if(lifeP>15){
            lifeRules.setText("You are spending too much on life");
        }else{
            lifeRules.setText("Life is fine");
        }
        if(savingsP<10){
            savingsRules.setText("You aren't spending enough on savings");
        }else{
            savingsRules.setText("Savings is fine");
        }
        
        
        
    }//GEN-LAST:event_EnterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FamilybudgetProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FamilybudgetProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FamilybudgetProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FamilybudgetProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FamilybudgetProgram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Enter;
    private javax.swing.JPanel budgetResults;
    private javax.swing.JPanel familyBudget;
    private javax.swing.JLabel heading;
    private javax.swing.JLabel heading2;
    private javax.swing.JLabel housingBar;
    private javax.swing.JTextField housingInput;
    private javax.swing.JLabel housingPrompt;
    private javax.swing.JLabel housingRules;
    private javax.swing.JLabel housingT;
    private javax.swing.JLabel lifeBar;
    private javax.swing.JTextField lifeInput;
    private javax.swing.JLabel lifePrompt;
    private javax.swing.JLabel lifeRules;
    private javax.swing.JLabel lifeT;
    private javax.swing.JTextField monthlyIncomeInput;
    private javax.swing.JLabel monthlyIncomePrompt;
    private javax.swing.JPanel monthlySpending;
    private javax.swing.JLabel prompt;
    private javax.swing.JLabel savingsBar;
    private javax.swing.JTextField savingsInput;
    private javax.swing.JLabel savingsPrompt;
    private javax.swing.JLabel savingsRules;
    private javax.swing.JLabel savingsT;
    private javax.swing.JLabel transportationBar;
    private javax.swing.JTextField transportationInput;
    private javax.swing.JLabel transportationPrompt;
    private javax.swing.JLabel transportationRules;
    private javax.swing.JLabel trasnportationT;
    // End of variables declaration//GEN-END:variables
}
